---ANALIZAR CLIENTES

SELECT 
		CL.COD_CLIENTE,
		CLI.STATUS_CLIENTE
		
FROM NPAZ.CLIENTE_LOCAL CL
INNER JOIN SYSADM.CLIENTE CLI
ON CL.COD_CLIENTE = CLI.COD_CLIENTE


-----------------------------------------------

---ACTIVAR CLIENTES 

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (SELECT DISTINCT * FROM NPAZ.CLIENTE_LOCAL)
    LOOP
        
	UPDATE SYSADM.CLIENTE C SET STATUS_CLIENTE='A'
        WHERE C.COD_CLIENTE=CUR.COD_CLIENTE;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;