DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (SELECT DISTINCT * FROM NPAZ.ACTUALIZAR_FACTOR_PROVEEDOR_ARTICULOS)
    LOOP
        UPDATE SYSADM.ARTICULOS A SET A.FACTOR_PROVEEDOR=CUR.FACTOR_PROVEEDOR 
        WHERE A.COD_ITEM=CUR.COD_ITEM;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;