--- ACTUALIZAR ORIGEN DE LOS ARTICULOS ( DE LAS BONIFICACIONES )

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (SELECT DISTINCT * FROM NPAZ.ACTUALIZAR_ORIGEN)
    LOOP
        UPDATE SYSADM.ARTICULOS AR SET AR.COD_ITEM_ORIGEN=CUR.COD_ITEM_ORIGEN
				
        WHERE AR.COD_ITEM=CUR.COD_ITEM;
				
        CANT := CANT +1;
				
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;