---- ARTICULOS A CONSULTAR DE FACTOR POR CARGAR

SELECT 
			NFP.COD_ITEM,
			A.DESC_ITEM,
			A.UM_COMPRA,
			NFP.FACTOR_PROVEEDOR AS FACTOR,
			A.FACTOR_PROVEEDOR

FROM NPAZ.ACTUALIZAR_FACTOR_PROVEEDOR_ARTICULOS NFP
INNER JOIN SYSADM.ARTICULOS A
ON NFP.COD_ITEM = A.COD_ITEM


--------------------------------------------------------------------------------

---- ARTICULOS SIN FACTOR PROVEEDOR BEBIDAS

SELECT 	A.COD_ITEM,
					A.DESC_ITEM,
				 --P.C_PROVEEDOR,
				 P.X_PROVEEDOR AS PROVEEDOR,
			   A.UM_VENTA,
				 A.UM_COMPRA,
				 A.FACTOR_PROVEEDOR
				 
FROM SYSADM.ARTICULOS A 
			INNER JOIN SYSADM.PROVEEDOR P
	     ON A.PROVEEDOR_DEFAULT=P.C_PROVEEDOR

WHERE PROVEEDOR_DEFAULT = '22770' 
	AND FACTOR_PROVEEDOR IS NULL
	AND STATUS_ITEM = 'A'
	
	
	--- ARTICULOS ACTIVOS CON FACTOR CONVERSION BEBIDAS 
	
	SELECT 	A.COD_ITEM as COD_ARTICULO,
					A.DESC_ITEM as ARTICULO,
				 --P.C_PROVEEDOR,
				 P.X_PROVEEDOR AS PROVEEDOR,
			   A.UM_VENTA,
				 A.UM_COMPRA,
				 A.FACTOR_PROVEEDOR as FACTOR
				 
FROM SYSADM.ARTICULOS A 
			INNER JOIN SYSADM.PROVEEDOR P
	     ON A.PROVEEDOR_DEFAULT=P.C_PROVEEDOR

WHERE PROVEEDOR_DEFAULT = '22770' 
	--AND FACTOR_PROVEEDOR IS NULL
	AND STATUS_ITEM = 'A'