--CREAR RUTA_DESPACHO DETALLE NUEVA

DECLARE
    vCANT NUMBER:=0;
    --vID NUMBER;
		vIDDET NUMBER;
    INICIO NUMBER := 66;
    
BEGIN
-- created_at
-- updated_at
-- deleted_at

    --SELECT MAX(IDRUTADESPACHO)+1 INTO vID FROM SYSADM.RUTA_DESPACHO;
		
    SELECT MAX(IDDETALLE)+1 INTO vIDDET FROM SYSADM.RUTA_DESPACHO_DETALLE;
		
    FOR CUR IN (
		SELECT * FROM NPAZ.CARGAR_RUTDESP_DETALLE RDD 
		JOIN SYSADM.TB_RUTA TR ON RDD.RUTAVENTA = TR.CODRUTA
		JOIN SYSADM.RUTA_DESPACHO RD ON RDD.RUTADESPACHO=RD.CODRUTADESPACHO 

	)	
    LOOP
       
				
				INSERT INTO SYSADM.RUTA_DESPACHO_DETALLE(
										IDDETALLE, 
										IDRUTADESPACHO,
										IDRUTAVENTA, 
										ESTADO, 
										FECHAASIGNACION, 
										USUARIOASIGNACION)
								VALUES(
												vIDDET+vCANT,
												CUR.IDRUTADESPACHO, 
												CUR.IDRUTA, 
												'A', 
												SYSDATE, 
												'PAZVILNO');
											
        
        vCANT := vCANT +1;
    END LOOP;
    --COMMIT;
    DBMS_OUTPUT.PUT_LINE ('CANTIDAD: '||vCANT);
END;