DECLARE
    vCANT NUMBER:=0;
    vID NUMBER;
    CODIGO VARCHAR(3):='';
    INICIO NUMBER := 66;
    p_DESCRIPCION VARCHAR2(50);
BEGIN
    
    SELECT MAX(IDRUTA)+1 INTO vID FROM SYSADM.TB_RUTA;
    FOR CUR IN (
		SELECT * FROM NPAZ.CARGAR_RUTA_VENTA R 
		JOIN SYSADM.TB_SEDE S ON R.SEDE=S.CODSEDE 
		JOIN SYSADM.TB_CANAL C ON C.IDCANAL=R.CANAL 

		)
    LOOP
        p_DESCRIPCION:=CUR.DESCRIPCION;
        IF LENGTH(p_DESCRIPCION)>40 THEN
            DBMS_OUTPUT.PUT_LINE(p_DESCRIPCION);
        END IF;
        SELECT XRAYADMIN.PK_UTILS.FN_GET_CODIGO_RUTA INTO CODIGO FROM DUAL;
        /*
        IF MOD(vCANT,100)=0 THEN
            INICIO := INICIO +1;
            SELECT CHR(INICIO)||SUBSTR(100+vCANT,-2,2) INTO CODIGO FROM DUAL;
        ELSE 
            SELECT CHR(INICIO)||SUBSTR(100+vCANT,-2,2) INTO CODIGO FROM DUAL;
        END IF;
        */
        
        INSERT INTO SYSADM.TB_RUTA(
            IDRUTA, CODRUTA, CODEMPRESA,
            IDSEDE, IDCANAL, DESCRUTA,
            ESTADO, DIARUTA, FECREGISTRO,
            USUARIOREG, TB_COD_GRUPO, UBIGEO,
            DIVISION)
        VALUES (
            vID+vCANT, CODIGO, CUR.EMPRESA,
            CUR.IDSEDE, CUR.IDCANAL, CUR.DESCRIPCION,
            'H', 'LU-MA-MI-JU-VI-SA-', SYSDATE,
            'PAZVILNO', '01', CUR.UBIGEO,
            'PA');
        
        INSERT INTO SYSADM.TABLAS(
            CATEGORIA, LLAVE, DESC1,
            DESC2, FECHA_MODIFICACION, DESCY,
            ROWVERSION, ESTADO)
        VALUES(
            '011', CODIGO, CUR.DESCRIPCION,
            SUBSTR(CUR.DESCRIPCION,1,40), SYSDATE, '10',
            0,'H');
        
        INSERT INTO SYSADM.SECTOR_X_RUTA(
            CSERU_RUTA, CSERU_CIUDAD, CSERU_SECTOR,
            CSERU_USUARIO,FSERU_TRANSACCION,ROWVERSION)
        VALUES(
            CODIGO,'010','0000',
            'PAZVILNO',SYSDATE,0);
         /*
        UPDATE LGONZALES.RUTAS_BEBIDAS_ROMPEDOR RT SET CODIGO_XRAY=CODIGO
        WHERE RT.DESCRIPCION=CUR.DESCRIPCION;
        */
        vCANT := vCANT +1;
    END LOOP;
    --COMMIT;
    DBMS_OUTPUT.PUT_LINE ('CANTIDAD: '||vCANT);
END;
