--CONSULTAR GIRO CLIENTE UNILEVER

SELECT 
			CU.CLIENTE,
			CU.TIPO_CLIENTE,
			C.TIPO_CLIENTE_UNI
FROM NPAZ.CLIENTE_UNILEVER CU
INNER JOIN SYSADM.CLIENTE C 
ON CU.CLIENTE = C.COD_CLIENTE

---------------------------------------------------------------------
--- ACTUALIZAR EL GIRO DEL NEGOCIO PARA CLIENTES DE UNILEVER ------

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (SELECT DISTINCT * FROM NPAZ.CLIENTE_UNILEVER)
    LOOP
        UPDATE SYSADM.CLIENTE C SET C.TIPO_CLIENTE_UNI=CUR.TIPO_CLIENTE 
        WHERE C.COD_CLIENTE=CUR.CLIENTE;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;