SELECT 
			RUT.IDRUTADESPACHO,
			RUT.CODRUTADESPACHO,
		  RUT.DESCRUTADESPACHO,	
			RUT.CODEMPRESA,
			SE.CODSEDE,
			RUT.CODFUERZAV

		FROM SYSADM.RUTA_DESPACHO RUT 
		INNER JOIN SYSADM.TB_SEDE SE ON RUT.CODSEDE = SE.CODSEDE
		where RUT.USUARIOREGISTRO = 'PAZVILNO'
		AND TO_DATE(RUT.FECHAREGISTRO, 'dd-mm-yy')=TO_DATE('19-08-2021', 'dd-mm-yy')