SELECT 
			RUT.IDRUTA,
			RUT.CODRUTA,
		  RUT.DESCRUTA,	
			RUT.CODEMPRESA,
			RUT.IDSEDE,
			RUT.IDCANAL,
			RUT.DIVISION,
			RUT.UBIGEO,
			RUT.ESTADO,
			RUT.DIARUTA,
			RUT.FECREGISTRO,
			RUT.USUARIOREG

		FROM SYSADM.TB_RUTA RUT 
		where RUT.USUARIOREG = 'PAZVILNO'
		--AND TO_DATE(RUT.FECREGISTRO, 'dd-mm-yy')=TO_DATE('20-12-2021', 'dd-mm-yy')
		AND TO_DATE(RUT.FECREGISTRO, 'dd-mm-yy')=TO_DATE('27-02-2022', 'dd-mm-yy')