SELECT 
			SRDD.IDDETALLE,
			SRDD.IDRUTADESPACHO,
			SRDD.IDRUTAVENTA,
			SRDD.ESTADO,
			SRDD.FECHAASIGNACION,
			SRDD.USUARIOASIGNACION
		FROM NPAZ.CARGAR_RUTDESP_DETALLE RDD 
		JOIN SYSADM.TB_RUTA TR ON RDD.RUTAVENTA = TR.CODRUTA
		JOIN SYSADM.RUTA_DESPACHO RD ON RDD.RUTADESPACHO=RD.CODRUTADESPACHO 
		JOIN SYSADM.RUTA_DESPACHO_DETALLE SRDD 
		ON SRDD.IDRUTADESPACHO = RD.IDRUTADESPACHO
		AND SRDD.IDRUTAVENTA = TR.IDRUTA
		
		WHERE 
		SRDD.USUARIOASIGNACION = 'PAZVILNO'
		AND TO_DATE(SRDD.FECHAASIGNACION, 'dd-mm-yy')=TO_DATE('21-08-2021', 'dd-mm-yy')
		
		