---ANALIZAR CLIENTES_LOCALES

SELECT 
		CL.COD_CLIENTE,
		LC.COD_LOCAL,
		CL.CODIGO_RUTA_ANTIGUA,
		LC.RUTA_DESPACHO,
		LC.DIVISION,
		LC.ESTAD,
		LC.DELETE_AT
		
FROM NPAZ.CLIENTE_LOCAL CL
INNER JOIN SYSADM.LOCALES_CLIENTE LC
ON CL.COD_CLIENTE = LC.COD_CLIENTE
AND CL.CODIGO_LOCAL = LC.COD_LOCAL

ORDER BY CL.COD_CLIENTE ASC, LC.DIVISION;

-----------------------------------------------

---INACTIVAR LOCALES DE CLIENTES 

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (SELECT DISTINCT * FROM NPAZ.CLIENTE_LOCAL)
    LOOP
        
	UPDATE SYSADM.LOCALES_CLIENTE LC SET ESTAD='I',
				LC.DELETE_AT= sysdate
        WHERE LC.COD_CLIENTE=CUR.COD_CLIENTE 
        AND LC.COD_LOCAL=CUR.CODIGO_LOCAL;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;