--====REVERTIR CAMBIOS CUANDO SE MIGRA A UNA NUEVA RUTA LOS LOCALES CLIENTS========-----
--------------------------------------------------------------------------------------------------
--CONSULTAR LOS LOCALES ACTUALES SIN MIGRAR, SE DEBE HABER CARGADO PREVIAMENTE EN LA TABLA PROVISIONAL 
--NPAZ.CLIENTE_LOCALES
SELECT 
		CL.COD_CLIENTE,
		CL.CODIGO_LOCAL,
		CL.CODIGO_RUTA_ANTIGUA,
		CL.CODIGO_RUTA_NUEVA,
		LC.FECHA_NEWGEO,
		LC.USUAR_GEOLO,
		LC.ESTAD,
		LC.DELETE_AT

		FROM NPAZ.CLIENTE_LOCAL CL
		INNER JOIN SYSADM.LOCALES_CLIENTE LC
		ON CL.COD_CLIENTE = LC.COD_CLIENTE AND CL.CODIGO_LOCAL = LC.COD_LOCAL

-----------------------------------------------------------------------------------------
--VOLVER A ACTIVAR LOS LOCALES DE CLIENTES QUE SE MIGRARON (CON RUTA_ANTIGUA

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (
		SELECT 
		CL.COD_CLIENTE,
		CL.CODIGO_LOCAL,
		CL.CODIGO_RUTA_ANTIGUA,
		CL.CODIGO_RUTA_NUEVA,
		LC.FECHA_NEWGEO,
		LC.USUAR_GEOLO,
		LC.ESTAD,
		LC.DELETE_AT

		FROM NPAZ.CLIENTE_LOCAL CL
		INNER JOIN SYSADM.LOCALES_CLIENTE LC
		ON CL.COD_CLIENTE = LC.COD_CLIENTE AND CL.CODIGO_LOCAL = LC.COD_LOCAL

		)
    LOOP
        
	UPDATE SYSADM.LOCALES_CLIENTE LC SET ESTAD='A',
				LC.DELETE_AT= NULL
        WHERE LC.COD_CLIENTE=CUR.COD_CLIENTE 
        AND LC.COD_LOCAL=CUR.CODIGO_LOCAL;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;

-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
---CONSULTAR LOS NUEVOS LOCALES CREADOS CON LAS NUEVAS RUTAS

SELECT 
		CL.CODIGO_RUTA_NUEVA,
		LC.COD_CLIENTE,
		LC.COD_LOCAL,
		LC.RUTA_DESPACHO,
		LC.FECGEOLOCALIZACION,
		LC.USUAR_GEOLO,
		LC.ESTAD

		FROM NPAZ.CLIENTE_LOCAL CL
		INNER JOIN SYSADM.LOCALES_CLIENTE LC
		ON CL.COD_CLIENTE = LC.COD_CLIENTE 
		AND CL.CODIGO_RUTA_NUEVA = LC.RUTA_DESPACHO
		--AND CL.CODIGO_LOCAL = LC.COD_LOCAL

		WHERE LC.USUAR_GEOLO = 'PAZVILNO'


--------------------------------------------------------------------------------------
---ELIMINAR LOS LOCALES DE LOS CLIENTES CON LA NUEVA RUTA CREADA

DECLARE
    CANT NUMBER :=0;
BEGIN
    FOR CUR IN (
		SELECT 
		CL.CODIGO_RUTA_NUEVA,
		LC.COD_CLIENTE,
		LC.COD_LOCAL,
		LC.RUTA_DESPACHO,
		LC.FECGEOLOCALIZACION,
		LC.USUAR_GEOLO,
		LC.ESTAD

		FROM NPAZ.CLIENTE_LOCAL CL
		INNER JOIN SYSADM.LOCALES_CLIENTE LC
		ON CL.COD_CLIENTE = LC.COD_CLIENTE 
		AND CL.CODIGO_RUTA_NUEVA = LC.RUTA_DESPACHO
		--AND CL.CODIGO_LOCAL = LC.COD_LOCAL

		WHERE LC.USUAR_GEOLO = 'PAZVILNO'

		)
    LOOP
        
	DELETE FROM SYSADM.LOCALES_CLIENTE LC
        WHERE LC.COD_CLIENTE=CUR.COD_CLIENTE
        AND LC.COD_LOCAL=CUR.COD_LOCAL;
        CANT := CANT +1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CANT);
		--COMMIT;
END
;
